
---
- hosts: all
  become: true


  tasks:
    # - name: stop already running container
    #   docker_container:
    #     name: spe-backend-temp
    #     state: stopped
    # - name: remove container
    #   docker_container:
    #     name: spe-backend-temp
    #     state: absent
    - name: Pull sahajv/spe_backend_temp
      docker_image:
        name: sahajv/spe_backend
        source: pull
    - name: Create a data container
      docker_container:
        name: spe-backend-temp
        image: sahajv/spe_backend_temp
        ports: "4000:4000"