
---
- hosts: all
  become: true


  tasks:
    - name: stop already running container
      docker_container:
        name: spe-backend
        state: stopped
    - name: remove container
      docker_container:
        name: spe-backend
        state: absent
    - name: Pull sahajv/spe_backend
      docker_image:
        name: sahajv/spe_backend
        source: pull
    - name: Create a data container
      docker_container:
        name: spe-backend
        image: sahajv/spe_backend
        ports: "4000:4000"